name: CI test curso
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: [docker, linux]
    container:
      image: node:20-bullseye   # imagem oficial Node com node instalado
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Runner info
        run: |
          node --version
          uname -a