name: Java CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [docker, java]
    container:
      image: maven:3.9.6-eclipse-temurin-17
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build (maven)
        run: mvn -B -DskipTests clean package
      - name: Run tests
        run: mvn -B test      