name: Java CI (git-clone robust)
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [docker, java]
    container:
      image: maven:3.9.6-eclipse-temurin-17
    env:
      REPO_URL: "http://giteahome.local/rubenss.leme/curso.git"
      WORKDIR: "/workspace"
    steps:
      - name: Prepare environment & install git
        run: |
          set -eux
          # ensure workspace exists and is writable
          mkdir -p "${WORKDIR}"
          ls -ld "${WORKDIR}"
          apt-get update
          apt-get install -y git
          git --version

      - name: Clone or refresh repository (supports private via GITEA_TOKEN)
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          set -eux
          # If repo already has a .git, try fetch+reset to avoid reclone; else clean and clone.
          if [ -d "${WORKDIR}/.git" ]; then
            echo "Repository already present — fetching updates"
            git -C "${WORKDIR}" fetch --all --prune
            # Try checkout the branch ref if available, else reset to origin/main
            git -C "${WORKDIR}" checkout --detach || true
            git -C "${WORKDIR}" reset --hard origin/main || true
          else
            echo "Workspace empty — performing clone"
            # ensure empty directory (remove leftover files)
            rm -rf "${WORKDIR:?}/"*
            if [ -n "${GITEA_TOKEN:-}" ]; then
              # private repo via token (token as "password" - username left empty)
              git clone "http://:${GITEA_TOKEN}@giteahome.local/rubenss.leme/curso.git" "${WORKDIR}"
            else
              git clone "${REPO_URL}" "${WORKDIR}"
            fi
          fi
          # make workspace safe for git in container
          git -C "${WORKDIR}" status || true

      - name: Build (maven)
        run: |
          set -eux
          cd "${WORKDIR}"
          mvn -B -DskipTests clean package

      - name: Run tests
        run: |
          set -eux
          cd "${WORKDIR}"
          mvn -B test
